{% extends request.ajax ? "layout_blank.phtml" : "layout_default.phtml" %}
{% import "macro_functions.phtml" as mf %}
{% block meta_title %}{% trans 'Orders settings' %}{% endblock %}
{% set active_menu = 'system' %}

{% block breadcrumbs %}
<ul>
    <li class="firstB"><a href="{{ '/'|alink }}">{% trans 'Home' %}</a></li>
    <li><a href="{{ 'system'|alink }}">{% trans 'Settings' %}</a></li>
    <li class="lastB">{% trans 'Orders settings' %}</li>
</ul>
{% endblock %}

{% block content %}

<div class="widget">
    <div class="head">
        <h5 class="iCog">{% trans 'Orders settings' %}</h5>
    </div>

    {% set params = admin.extension_config_get({"ext":"mod_order"}) %}
    <form method="post" action="admin/extension/config_save" class="mainForm api-form" data-api-msg="Settings updated">
        <fieldset>
        <div class="rowElem noborder">
            <label>{% trans 'Expiration date' %}</label>
            <div class="formRight">
                <input type="radio" name="order_renewal_logic" value="from_expiration_date" {% if params.order_renewal_logic == "from_expiration_date" or not params.order_renewal_logic %}checked="checked"{% endif %}/><label>Next date is counted from last order expiration date</label>
                <div class="clear"></div>
                <input type="radio" name="order_renewal_logic" value="from_today" {% if params.order_renewal_logic == "from_today" %}checked="checked"{% endif %}/><label>Next date is counted from renewal (payment) date</label>
                <div class="clear"></div>
                <input type="radio" name="order_renewal_logic" value="from_greater" {% if params.order_renewal_logic == "from_greater" %}checked="checked"{% endif %}/><label>Next date is counted from last expiration date or renewal date whichever is greater</label>
            </div>
            <div class="fix"></div>
        </div>

        <div class="rowElem">
            <label>{% trans 'Auto suspend reason' %}</label>
            <div class="formRight">
                <input type="text" name="batch_suspend_reason" value="{{ params.batch_suspend_reason }}" />
            </div>
            <div class="fix"></div>
        </div>

        <input type="hidden" name="ext" value="mod_order" />
        <input type="submit" value="{% trans 'Update settings' %}" class="greyishBtn submitForm" />
        </fieldset>
    </form>
</div>

{% endblock %}