{% if order.status == 'active' %}
{% set info = admin.serviceboxbillinglicense_order_info({"order_id":order.id}) %}
<div class="widget">
    <div class="head">
        <h2 class="dark-icon i-services">{{ order.title }}</h2>
    </div>
    
    <table>
        <tbody>
            <tr>
                <td>{% trans 'License key' %}:</td>
                <td>{{ info.license_key }}</td>
            </tr>
            <tr>
                <td>{% trans 'Valid IPs' %}:</td>
                <td>{% for v in info.ips %}{{ v }}{{constant("PHP_EOL")}}{%else%}All IPs{% endfor %}</td>
            </tr>
            <tr>
                <td>{% trans 'Valid hostnames' %}:</td>
                <td>{% for v in info.hosts %}{{ v }}{{constant("PHP_EOL")}}{%else%}All hostnames{% endfor %}</td>
            </tr>
            <tr>
                <td>{% trans 'Valid versions' %}:</td>
                <td>{% for v in info.versions %}{{ v }}{{constant("PHP_EOL")}}{%else%}Any version{% endfor %}</td>
            </tr>
            <tr>
                <td>{% trans 'Valid install paths' %}:</td>
                <td>{% for v in info.paths %}{{ v }}{{constant("PHP_EOL")}}{%else%}Any install path{% endfor %}</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="2">
                    <a href="client/serviceboxbillinglicense/order_reset?order_id={{order.id}}" data-api-confirm="Are you sure?" data-api-msg="License details was reset" class="bb-button bb-button-submit">Reset</a>
                </td>
            </tr>
        </tfoot>
    </table>
</div>
{% endif %}